### ISSUE TITLE
> ```

### ISSUE THREAD

**Issue by Samet1994** [johnynek/bosatsu#1113]
> ```
> [info] - x n y == y n x *** FAILED *** (10 milliseconds)
> [info]   TestFailedException was thrown during property evaluation.
> [info]     Message: List(Cat(AnyElem, Cat(Wildcard, Cat(Lit(Set(true, false)), Empty)))) did not equal List(Cat(AnyElem, Cat(Wildcard, Cat(AnyElem, Empty)))) List(.*Set(true, false)) != List(.*.)
> [info]     Location: (SeqPatternTest.scala:373)
> [info]     Occurred when passed generated values (
> [info]       arg0 = Cat(Wildcard, Cat(Wildcard, Cat(AnyElem, Cat(Lit(Set(true, false)), Empty)))),
> [info]       arg1 = Cat(AnyElem, Cat(Wildcard, Cat(AnyElem, Empty)))
> [info]     )
> [info]   Init Seed: 963554269334762220
> ```6104337747981841

_Originally posted by @Samet1994 in https://github.com/johnynek/bosatsu/issues/1104#issuecomment-1906680311_

**Comment by johnynek** [comment]
this seems to be some kind of error comment. Please re-open if you have more of an issue.
