### ISSUE TITLE
Escaping of " is a non-op

### ISSUE THREAD

**Issue by snoble** [johnynek/bosatsu#139]
https://github.com/johnynek/bosatsu/blob/8a6512d466054bf069e7addee14aeb32d6a1631a/core/src/main/scala/org/bykn/bosatsu/Json.scala#L19

Pretty sure this should be `case '"' => "\\\""`

**Comment by johnynek** [comment]
To clarify: this is in the json output mode.

Thanks, yeah, that doesn't look right to me.

**Comment by snoble** [comment]
> To clarify: this is in the json output mode.
yes
