### ISSUE TITLE
add a Dict[String, a] literal

### ISSUE THREAD

**Issue by johnynek** [johnynek/bosatsu#14]
would be nice to have:
```
{"a": 1, "b": c, ...}
```
to return a hash or sorted Dict type.

**Comment by johnynek** [comment]
Since I think it is unlikely I will ever add typeclasses directly to bosatsu, a fully generic encoding of a mapping type would require dictionary passing, either when constructing the dict or when accessing the dict.

The alternative is to fix the key type to for instance String. Since this is purely a syntactic trick, I think fixing key type to string is the way to go. We can still implement fully generic maps with dictionary passing if needed.

As an example of dictionary passing:
```
struct Order(compare: a -> a -> Comparison)

# e.g. an AVLTree,
enum Map: ...

# the empty map embeds the Order
def empty_Map(ord: Order[k]) -> forall v. Map[k, v]:
 ...
def add_Map(m: Map[k, v], k, v) -> Map[k, v]: ...

def get_Map(m: Map[k, v], k) -> Option[v]:
```

A crazier syntax could be passing the dictionary optionally to the literal:
```
str_map = {"one": 1, "two": 2, "four": 4}
int_map = {1: "one", 2: "two", 3: "three"} @ intOrd
```
I don't love this idea since it basically sneaks in typeclasses, but only for a few cases: string gets a free ordering, and dict has a way to pass in typeclasses, but they don't exist elsewhere in the language.

By sticking with only allowing string keys, we also leave the door open to changing our minds about typeclasses later and still string key dicts would work.

Given the intended use cases, I tend to think the dict should always be sorted by key, so the order in which things are computed or added is not observable at the output (which we often want in configurations). If the user intends to track order, they should use a list.

**Comment by avibryant** [comment]
+1 to your reasoning above.
