### ISSUE TITLE
Type inference fails for `forall` types

### ISSUE THREAD

**Issue by snoble** [johnynek/bosatsu#209]
This might be asking too much of type inference... but figured I'd make an issue anyhow

```
package Example/Wrap

def wrap(x):
  Some(x)

def doToSomething(fn: forall a. a -> b[a]):
  (fn(1), fn("two"))

out = doToSomething(wrap)
```

is a valid program. But if we do
```
package Example/Wrap

def wrap(x):
  Some(x)

def doToSomething(fn):
  (fn(1), fn("two"))

out = doToSomething(wrap)
```

we get

```
in file: ../bosatsu_examples/wraptest.bosatsu, package Example/Wrap, type Bosatsu/Predef::Int does not unify with type Bosatsu/Predef::String
5|
6|def doToSomething(fn):
7|  (fn(1), fn("two"))
               ^^^^^
```

The work around? In these cases, just write the type

**Comment by johnynek** [comment]
This is a complex type to infer. Thanks for the examples. The paper discusses some similar problems. For instance the algorithm will not infer, IIRC a rank-N type even though it is a legal type.

That said, the paper didn’t contemplate user defined types. And this is an interaction there I think. So it may be possible to change the algorirthm to improve cases like this without regressing in other areas.

**Comment by johnynek** [comment]
I wonder if this is related to this comment:

https://github.com/johnynek/bosatsu/issues/106#issuecomment-470354751

We don't use variance information in custom type inference, but we do for functions. Basically, the contravariance of the input and covariance of the output is known.

I think this code: https://github.com/johnynek/bosatsu/blob/b81e52372d7940377ca3e5ea54cc96103d9ed961/core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala#L384

probably needs to know about `Apply(t1, t2)` types and it needs to know the variance of `t1` in that case. We have already solved variance, and I think we are passing it in, but it is currently being ignored in the inference for substitution.

The second thing, for a covariant type, `t[forall a. a]` is the same as `forall a. t[a]`. We do this normalization in functions here:
https://github.com/johnynek/bosatsu/blob/b81e52372d7940377ca3e5ea54cc96103d9ed961/core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala#L289

I think we should be doing that for all Apply types for their covariant parts.

It would be good to come up with some minimal test cases we *think* should pass and get those to pass.

This #144 had some cases I commented out:
https://github.com/johnynek/bosatsu/pull/144/files#diff-2e5a2cfea7b61b4aaf84820d8fdd73ddR659
https://github.com/johnynek/bosatsu/pull/144/files#diff-2e5a2cfea7b61b4aaf84820d8fdd73ddR723

maybe uncommenting those, and getting them to pass, then we could see if your examples work, or maybe we can minimize your example, or even put it in directly.
