### ISSUE TITLE
rename Tuple2 to TupleCons

### ISSUE THREAD

**Issue by johnynek** [johnynek/bosatsu#213]
`Tuple2(a, b)` looks like it might be the same as `(a, b)` but actually `(a, b)` is implemented at `Tuple2(a, Tuple2(b, Unit))`

If we rename `Tuple2` to `TupleCons` maybe it makes it clearer this may not be what you think.

What do you think @snoble ?

**Comment by snoble** [comment]
I think that's right

**Comment by johnynek** [comment]
this was motivated by: https://github.com/johnynek/bosatsu/issues/196#issuecomment-478389862
