### ISSUE TITLE
add build and basic run instructions to the README

### ISSUE THREAD

**Issue by snoble** [johnynek/bosatsu#27]
The two steps I've tried is `sbt run` which results in `No main class detected.` and `sbt package` followed by `java -jar core/target/scala-2.12/bosatsu-core_2.12-0.1.0-SNAPSHOT.jar` which results in

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/monovore/decline/Command
```

**Comment by johnynek** [comment]
try `core/run`

running the jar won't work, it is not a fat jar.

**Comment by snoble** [comment]
that works
