### ISSUE TITLE
chaining calls over multiple lines

### ISSUE THREAD

**Issue by snoble** [johnynek/bosatsu#274]
Python lets you chain calls over multiple lines with the `\` just like
```
return some_collection.get_objects(locator=l5) \
                      .get_distinct(case_insensitive=True) \
                      .filter(predicate=query(q5)) \
                      .values()
```
Seems nice

**Comment by johnynek** [comment]
What do you think about allowing new lines/space after `.` so you can chain with a trailing `.`?

I think the \ is a bit junky but it shouldn’t be hard to let the parser support it.

After I get out of proto-hell....

😂

**Comment by snoble** [comment]
I like trailing periods. I also like stealing python syntax. So I'm happy with every option.

I think the Ruby/Scala style is a mistake (although I like the looks of it), because it seems to generalize to lines that start with an operator continue the previous line, which has led to confusion around starting a line with `-`. Which is less of a problem with bosatsu.

I guess that is a question around trailing periods: does it extend to all operators?

**Comment by snoble** [comment]
(alllllso, good luck with the proto-hell :p)

**Comment by johnynek** [comment]
Okay, so, I think I want to do this very soon. My idea is that any line that potentially adds indentation and starts with a `.` is continuing an apply chain from the previous line.

```
x = foo
    .doSomething(x)
    .doSomethingElse
    .bar
```

No expressions can begin with a `.` so I think this is unambiguous and we don't need to junk things up with a `\` character.

**Comment by johnynek** [comment]
ahh... in a repl, you need the `\` to denote that more input is coming. So, I guess we should make the trailing `\` optional for that case.
