### ISSUE TITLE
use names on constructors

### ISSUE THREAD

**Issue by johnynek** [johnynek/bosatsu#289]
related to #240 

Currently, we have syntax like:
```
struct Foo(bar: Int)
```
But `bar` is never used anywhere in the code later. There is no way to do so.

Goals:

1. use the names at construction time
2. use the names when pattern matching to give "getters" for values.
3. minimize unfamiliarity (primarily Python, but possibly Rust for inspiration).

We explored some syntax in #240 for matching, but I think matching and creation should be designed together.

There is a related question: can use also support named arguments to `def` function values? This is very hard to do for general values that may be functions, so this would introduce a distinction between let bindings that point to functions vs functions. This is likely similar to a distinction between using a constructor with names vs assigning a constructor to a let binding and using it as a function.

Here are some decision axes:

## Creation looks like python/function calls
Python-like syntax for creation:
```python
x = Foo(bar = 3)
```
If we use that creation syntax, I think (see arguments in #240) that the pattern match version should be:
```
x = Foo(bar = 3)
Foo(bar = y) = x
# or
y = match x:
  Foo(bar = z): z

# now y = 3
```
A different variant of this is `Foo(bar: 3)`. It has something going for it, but does seem to mix metaphors of function calls and dict creation. I can see an argument that we should either be very close to python, or significantly different.

## Creation looks like Rust/Haskell
Rust/Haskell like record creation:
```
x = Foo { bar = 3 }
Foo { bar = y } = x 
#Colon syntax more like dicts:
x = Foo { bar: 3 }
Foo { bar: y } = x
```
One benefit, or issue, with this approach is that it doesn't invite the idea that function calls would work the same. A challenge to function calls supporting names is that we can't easily support named functions through let bindings:
```
def f(arg: Int): Int = arg

g = f
# this seems tractable: we can look up the name in the environment
f(arg = 3)
# this does not seem tractable since the names would become part of the type of the binding and that would seriously change inference and how we think about function types:
g(arg = 3)
```
If we use `Foo { bar = 3 }` or `Foo { bar: 3 }` it doesn't invite the idea that `f { arg = 3 }` or `f { arg: 3 }` would work since that syntactically looks so strange. Next, `Foo` is kind of like a dictionary, which we have literals for, so giving a name to them and reusing the syntax looks reasonable to me.

The main downside to this approach is that `Foo(3)` and `Foo { bar: 3 }` are the same, but syntactically they look different. `Foo(bar = 3)` seems to make that more similar.

## Matching must explicitly match everything or not
We probably need the ability to ignore other fields, we can either explicitly or implicitly do so:
```
struct Bar(i: Int, s: String)
x = Bar(1, "str")
# explicit, require ... to ignore 0 or more, or possibly be more strict and say 1 or more, parameters
Bar(i = j, ...) = x
# implicit, just ignore any unnamed fields on matching:
Bar(i = j) = x
```
## Disallow (or not) mixed named and unnamed parameters

One question: do we support mixing named and unnamed parameters? I would argue no: all named or all unnamed, this avoids any ambiguity about how to handle mixing of named and unnamed. An alternate approach is that after a named parameter, all the remaining parameters must be named. But there is still a question about order, and pattern matching.

## Directionality in matching
I mention this, which is one of the core questions in #240, should matching reverse or not:
```
x = Foo(bar = 3)
# here we are reversing the name to be on the right, so it look more like y is being assigned
Foo(y = bar) = x
# however, this looks more like a pattern match to me, and matches for instance javascript:
Foo(bar = y) = Foo(bar = 3)
```
An alternate is to use a different (or no) symbol for setting fields: `Foo(bar := 3)` or `Foo(bar 3)`. There are some nice arguments for those in #240, but I do worry that this increases our distance from Python, and trying to keep as many of the python syntactic wins as we can is a major goal of Bosatsu.

Comments welcome. Especially from @snoble.

**Comment by johnynek** [comment]
One thing to note is syntactic ambiguity here: both `=` and `:` are already used. `=` for assignment and `:` for typing `x: Int` but also in dicts: `{ "foo": 3 }`. We already trigger parsing differently inside `{ }`.

But if you look at `Foo(bar: T)` this could mean set bar to the value `T` which might be an item in a type constructor, or it could mean call `Foo` with the value `bar` which is of type `T`. It is not possible to disambiguate this, I don't think, locally.

Like for dicts, we could do `Foo { bar: T }` because we could use different parsing rule inside `{ }` immediately following a constructor (capital name), and we could require `identifier: value` which does seem tractable.

`Foo(bar = 3)` does seem parsable because `bar = 3` isn't actually an expression, it is the first part to a let, so you can tell that apart.

That seems to imply of the above, our two choices are:
1. `Foo(bar = 3)`
2. `Foo { bar: 3 }` or `Foo{bar: 3}` for those that like compact curlies.

**Comment by johnynek** [comment]
we could disallow function calls with arguments and only use record syntax if you want names:
```
struct Arg(name: String, age: Int)

def foo(args: Args): ...

foo(Args{ name: "Alice", age: 46 })
```

**Comment by ianoc** [comment]
This all seems really sane to me. The directionality one is a curious one. Neither of them look entirely 'natural' to me, so i guess i wouldn't have a particularly strong preference there. 
I'd probably go with:
`Foo(y = bar) = x` mostly just because the assignment operator looks to somewhat be inverted otherwise. (depends on how you interpret its meaning on the line too).


I'd be inclined to keep function calls with arguments as thats what people expect. Though the overhead in coding of losing it doesn't seem high.

**Comment by non** [comment]
My personal preferences would be:

```
cat = Cat { name: "Whiskers", kind: "Tabby" }
Cat { kind: myKind, ... } = cat
```

That is, I like using `{}` and `:` instead of `()` and `=`. I also think having to explicitly discard "the rest" of the constructor parameters with `...` is better than doing it implicitly. Finally, at least using `:`, I think preserving the order (label on left, value on right) is better than reversing things.

**Comment by johnynek** [comment]
In #301 I introduce parsing of the dict-like syntax that @avibryant and @non supported. That seemed to have the least issues and the easiest to explain and teach.

Thank you all for thinking and commenting on this design choice. I think it is the last significant syntax question. After I implement this, I plan to implement libraries and see how everything feels at a bigger scale.

**Comment by johnynek** [comment]
This was done by https://github.com/johnynek/bosatsu/projects/1
