### ISSUE TITLE
update to fastparse 2 or move to a new parsing library

### ISSUE THREAD

**Issue by johnynek** [johnynek/bosatsu#545]
fastparse 1 is blocking updating the scala protobuf library.

I'm a bit worried about fastparse 2 being macro based and not being able to update to scala 3.

I've threatened to write another parsing library that doesn't use macros and use that. Maybe I'll do that within this project following the the code I wrote for this talk:

https://www.youtube.com/watch?v=kTyvu0uxPzg

**Comment by johnynek** [comment]
this is also blocking scalajs 1.0.0

**Comment by ngbinh** [comment]
can't wait for this. I am already on scala.js 1.2.0

**Comment by johnynek** [comment]
#588 updates to scalajs 1.2.0.
