### ISSUE TITLE
Allow a var name to show up twice in a pattern and only match when the positions are equivalent

### ISSUE THREAD

**Issue by snoble** [johnynek/bosatsu#584]
Currently you could have a function `after_first_3` that looks like

```
def after_first_3(lst):
  match lst:
    [_*, 3, x*]: Some(x)
    _: None
```

but `after_first_n` is difficult. But what if you could do

```
def after_first_n(n, lst):
  match (n, lst):
    (k, [_*, k, x*]): Some(x)
    _: None
```

Implementation seems not too bad since there's a natural injection from bosatsu values to patterns, you would search for any matched value for the first mention and then substitute the variable with the pattern inferred by that match.

It could be very expensive in some cases.

**Comment by snoble** [comment]
Note that variable names can be repeated in a pattern currently but it just shadows which seems confusing.

**Comment by johnynek** [comment]
the intent is to only allow shadowing in unions `Foo(x) | Bar(x)` not real shadowing...

The problem with this is that it assumes we have solved the equality problem, which we currently haven't.

equality needs either typeclasses ( #440 ) or it needs some notion of kinds of types ( #442 )

**Comment by snoble** [comment]
oh yeah, that makes sense. I was thinking equality was straight forward but of course there are functions that can matched to a variable and there's no equality for that.

I just double checked and shadowing is happening in other cases. eg
```
package Foo

out = match (1,2):
  (a, a): a
```
evaluates to
```
steven@ScalaCompiler:~/bosatsu$ ./bosatsuj eval --main_file ../Foo.bosatsu
2: Bosatsu/Predef::Int
```

**Comment by johnynek** [comment]
yeah, in the short term this should definitely be banned. I'll look at adding a check to the sourceconverter code to make sure that each non-union pattern has a unique set of names.

**Comment by johnynek** [comment]
closing this since I think #592 handled this the way I think it should be handled. Built in equality that is type-safe and parametric is something that so far I haven't made any progress on in #442
