### ISSUE TITLE
change `@` to `as`in pattern matches

### ISSUE THREAD

**Issue by johnynek** [johnynek/bosatsu#623]
so far if you bind a name to a pattern, we use `@` similar to scala and haskell. But when we alias an import we use `as`. It seems maybe we should remove `@` from patterns and just use as:

```
match f:
  Foo(Bar(_) as bar): fn(bar)
  _: ...
```

you can imagine allowing `as` as a let binding in general:

```
foo(x) as f
g(f)
```

but having two ways of doing assignment seems bad.

That said, maybe we should use `=` in patterns:

```
match f:
  Foo(bar = Bar(_)): - 
```
which leaves `as` only in imports...

Thoughts @snoble

**Comment by snoble** [comment]
It looks like the current pep for python is to use `as` so that seems like a good choice.

https://www.python.org/dev/peps/pep-0634/#as-patterns
