### ISSUE TITLE
Equality on all values

### ISSUE THREAD

**Issue by johnynek** [johnynek/bosatsu#80]
I believe that bosatsu, like the simply typed lambda calculus, is strongly normalizing (we forbid recursion, are total, but we can infer a few more types due to using the rank n algorithm of Peyton Jones et. al.)

I think this means that if we have some normalization rules no matter the order applied we always reach the same final state.

We could use this property to define equality on all *identically types pairs*: if after being fully normalized they are structurally identical, we return True else False.

```
external def eq(left: a, right: a): Bool
```
Having a free equality would be very nice. But there may be some issues I am missing with this.

One clear issue is that this would allow us to have equality on functions despite there being more than one structural way to express the same function (if by same we mean returns the same values for all inputs).

Apologies for the many claims above given without proof or reference. Some may be wrong and I’d be glad to be corrected.

**Comment by snoble** [comment]
Here's an example of why I would be skeptical. Consider two functions that summed up finite arithmetic sequences. One that simply folded over the sequence and the other that used the O(1) formula. Clearly these two functions have the same inputs and outputs but unless the formula for the sum of finite arithmetic sequences was a normalization rule they wouldn't have equivalent representations.

**Comment by johnynek** [comment]
we could use python's `is` here.

@snoble you are right, it is not a complete equivalence, and functions are where things really go wrong, but many languages have something like this that works for some types.

One reason not to do add it is that it would constrain all implementations to having a very good normalization, which I guess we plan on doing anyway, so maybe that isn't a reason not to.

btw: @snoble your caching demo was effectively doing this in order to store results in a hashmap.

**Comment by johnynek** [comment]
This seems like a bad idea.
